# Generated by Django 3.1 on 2021-05-04 10:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field', '0002_auto_20210504_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.field')),
            ],
            options={
                'unique_together': {('field', 'crop_name')},
            },
        ),
        migrations.CreateModel(
            name='CropSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_description', models.TextField()),
                ('sowing_date', models.DateField(default=datetime.date.today)),
                ('season', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=field.models.current_year, verbose_name='year')),
                ('crop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.crop')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.field')),
            ],
        ),
        migrations.CreateModel(
            name='CropRotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sowing_date', models.DateField(default=datetime.date.today)),
                ('crop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.crop')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.field')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.cropseason')),
            ],
        ),
    ]
