# Generated by Django 3.1 on 2021-05-04 10:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(default='', max_length=25)),
                ('activity_type', models.CharField(default='', max_length=25)),
                ('description', models.TextField(default='')),
                ('planned_cost', models.FloatField(default=0.0)),
                ('actual_cost', models.FloatField(default=0.0)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('group_name', models.CharField(max_length=100, null=True)),
                ('farm_size', models.FloatField(default=0.0)),
                ('field_coordinate', models.JSONField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignFarmActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_member_id', models.CharField(max_length=25)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='field.activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='field.field'),
        ),
    ]
