# Generated by Django 3.1 on 2021-05-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_coordinate',
            field=models.JSONField(default=dict),
        ),
    ]
